spring.application.name=api_blog
spring.datasource.url=jdbc:postgresql://localhost:5432/api_blog
spring.datasource.username=postgres
spring.datasource.password=Pa$$w0rd#@!
spring.security.user.name=admin